language: node_js

node_js:
  - 11.10.0

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - yarn install

cache:
  directories:
    - node_modules

env:
  ci: true

script:
  - npm run e2e || echo '这一步失败不影响后续步骤。'
  - npm run build
  - mkdir -p dist/pages/callback
  - mkdir -p dist/pages/cards
  - mkdir -p dist/pages/accounts
  - cp -r dist/index.html dist/pages/callback/citi.html
  - cp -r dist/index.html dist/pages/callback/uni.html
  - cp -r dist/index.html dist/pages/cards/cards.html
  - cp -r dist/index.html dist/pages/cards/product-list.html
  - cp -r dist/index.html dist/pages/accounts/bind.html
  - ls dist

  - docker build -t "$DOCKER_USERNAME"/me . || 'docker build 失败不影响后续步骤'
  - docker images
  - docker run -d -p 127.0.0.1:10086:10086 --name me "$DOCKER_USERNAME"/me
  - docker ps | grep -q me
  - docker push "$DOCKER_USERNAME"/me

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
          keep-history: true
          local_dir: dist
          on:
            branch: master
          fqdn: pa-ca.me
