language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - ACCESS_TOKEN=e21f97ba7cc247b188de7014b014fdd7 &&  ENVIRONMENT=production &&   LOCAL_USERNAME=`travis` &&
    REVISION=`git rev-parse --verify HEAD` && curl https://api.rollbar.com/api/1/deploy/ \
    -F access_token=$ACCESS_TOKEN \
    -F environment=$ENVIRONMENT \
    -F revision=$REVISION \
    -F local_username=$LOCAL_USERNAME

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local_dir: dist
    on:
      branch: master
