language: node_js

node_js:
  - 11.10.0

services:
  - docker

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cache:
  directories:
    - node_modules

env:
  ci: true

script:
  - npm run e2e
  - npm run build
  - mkdir -p dist/pages/callback
  - cp -r dist/index.html dist/pages/callback/citi.html
  - ls dist

  - docker build -t "$DOCKER_USERNAME"/me .
  - docker images
  - docker run -d -p 127.0.0.1:10086:10086 --name me "$DOCKER_USERNAME"/me
  - docker ps | grep -q me
  - docker push jefftian/me

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local_dir: dist
    on:
      branch: master
    fqdn: pa-ca.me
