export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USER = 'SET_USER'
export const LOGGEDIN = 'LOGGEDIN'
export const LOGGIN_CANCELLED = 'LOGGIN_CANCELLED'
export const SET_LOADING = 'SET_LOADING'
export const SET_CHECKING = 'SET_CHECKING'
