on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Generate artifacts
        env:
          ci: true
        run: |
          npm i
          npm run e2e
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "test/*.gif"
